name: Release Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: release-pipeline
  cancel-in-progress: false

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-dotnet@v3
        name: Setup dotnet
        with:
          dotnet-version: '7.0.x'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: dotnet restore
        name: Restore project
      - run: dotnet build
        name: Build project
      - name: Test project
        uses: ./.github/actions/script-to-summary
        with:
          summary-header: Test Output
          run: dotnet test --no-restore --no-build -v minimal
      - name: Build container
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          dotnet publish Api -c release -o output
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=sha,format=long
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}